#ifndef __PARA__
#define __PARA__
const char *e_para[5] = 
{ 
	"The fastest typing speed ever, 216 words per minute, was achieved by Stella Pajunas-Garnand from Chicago in 1946 in one minute on an IBM electric. As of 2005, writer Barbara Blackburn was the fastest English language typist in the world, according to The Guinness Book of World Records. Using the Dvorak Simplified Keyboard, she had maintained 150 wpm for 50 minutes, and 170 wpm  for shorter periods, with a peak speed of 212 wpm. Blackburn, who failed her QWERTY typing class in high school, first encountered the Dvorak keyboard in 1938, quickly learned to achieve very high speeds, and occasionally toured giving speed-typing demonstrations during her secretarial career. She appeared on Late Night with David Letterman on January 24, 1985, but felt that Letterman made a spectacle of her. Blackburn died in April 2008", 
	"Scolding is something common in student life. Being a naughty boy, I am always scolded by my parents. But one day I was severely scolded by my English teacher. She infect teaches well. But that day, I could not resist the temptation that an adventure of Nancy Drew offered. While she was teaching, I was completely engrossed in reading that book. Nancy Drew was caught in the trap laid by some smugglers and it was then when I felt a light tap on my bent head. The teacher had caught me red handed. She scolded me then and there and insulted me in front of the whole class. I was embarrassed. My cheeks burned being guilty conscious. When the class was over, I went to the teacher to apologize. When she saw that I had realized my mistake, she cooled down and then told me in a very kind manner how disheartening it was when she found any student not paying attention. I was genuinely sorry and promised to myself never to commit such a mistake again.", 
	"Pollution is a significant threat to our environment and is caused by the reckless attitude of man towards nature. Our Earth provides us with food and shelter, whereas we treat it mercilessly and plunder its resources. Pollution is a direct result of our greed. We dump waste into our water bodies without caring for the organisms living in them. The balance of various gases in the atmosphere has been disrupted because of the large number of vehicles plying on the road. Even factories that release harmful gases into the atmosphere contribute to air pollution. When we do excessive and uncontrolled farming on a piece of land, it loses its natural minerals. So, when we use fertilizers to boost their productivity, it pollutes the soil. Noise pollution is caused by factories, jets, airplanes, etc. It harms our ears and can impair hearing.", 
	"Tigers are animals that live in the wild. They are hungry animals that prey on smaller organisms. Their food usually consists of deer and boars. These animals grow up fast and attain maturity at around 3 or 4 years. They can live for up to 20 years in the wild. Males of the species are heavier than their female counterparts as they have different body functions. The young ones of tigers are known as cubs and require special care at the time of their birth. This is the reason why most of the cubs don't survive in the wild. They are endangered species, and their number has been declining for the past decade. Efforts are being made to conserve these mammals, and it has seen some improvement in countries like Nepal, India, Russia, and China. These animals are ferocious yet sensitive, so they must remain in the wild without any human interference.", 
	"Christmas is the most important festival for Christians. It brings home a spirit of cheer across the entire world. Christmas dates back to the time when Jesus was born to Mother Mary in a small stable. This festival is celebrated to mark the arrival of Jesus into this world. It is believed that the birth of Jesus Christ was prophesized earlier. Therefore, this festival is dear to traditional Christians. It has found widespread popularity among all the people irrespective of their religion or community. It is the time when families get together and cook delicious food for each other. The Christmas tree is a big attraction point of Christmas. People install Christmas trees at their homes and decorate it with bells, balls, glitter, and stars. It is all about baking sweet cakes and sharing them with your loved ones.", 
}; 
const char *m_para[5] =  
{
	"A healthy body and mind are essential to achieve complete wellbeing. If we are healthy, we can resist our bodies from being attacked by germs. Our bodies are really sensitive and therefore, must be handled with necessary precautions. We can develop healthy habits like eating and sleeping on time to boost our overall health. This helps in becoming a healthier version of ourselves. Holistic growth can be achieved if we focus on all the aspects of our health. Such as nutrition, wellness, spirituality, and mental health. There are plenty of exercises that will boost our physical health and help us to become stronger. A stronger body would lead to less fatigue while performing any activity. It is advised that we must exercise for at least 2 hours every day for better health. We can even join fitness classes to take professional help and practice the art of health and wellness in a better way.", 
	"Yoga is the ultimate act of harmony between one's physical existence and spiritual conscience. The perfect synchronization between the mind and the body is known as yoga. More than a physical form of exercise, it is considered as a spiritual act that makes you aware of yourself. The deep introspection that we do when our mind is relaxed makes us feel connected to our inner selves. Yoga took shape in ancient India during the early Indus Valley civilizations. It became popular after it was documented in detail by the Hindu priests who originally practiced yoga. In India, Yoga has been adopted as a way of life rather than a form of exercise.", 
	"The environment is the natural surroundings of the earth that enables an organism's survival. The French word ‘environ' that means to surround is a derivative of the word environment. It consists of living beings such as humans, plants, and animals. The air, water, and land are non-living entities. Their functioning is designed by nature in such a way that everything is dependent on each other. The human being is the most dominant creature of all the beings who can depend on all the natural resources of the earth. He requires the air to breathe. Not only humans but plants and animals also need air to breathe. There will be no life on earth without air. It is only the human being who is responsible for the destruction of the environment.", 
	"The earth consists of surroundings in which all living and non-living beings live their lives. The physical, biological, and natural forces of nature combine together and create circumstances that enable an organism to live. Such circumstances are called the environment. The French word ‘environ' which means to surround is a derivative of the word environment. All the biotic (living) and abiotic (non-living) entities constitute the environment. Biotic things include- humans, plants, animals, and insects. They are classified as biological components of the environment. Every biotic creature has its own fixed life cycle. For example, human-being is the strongest living organism on earth. He needs plants and animals in order to fulfill his needs. His life-cycle will be disorganized without them.", 
	"The highest share in global unemployment is that of young people in emerging or underdeveloped countries where they live in moderate or poor conditions despite having an undeserving job. The wide disparity between young men and women has mostly contributed to unemployment. This problem has been faced, particularly by African and Asian countries where female discrimination is prevalent. According to the International Labor Organization (ILO) report, the rates of female employment is 32.9 percentage points lower than that of males in the year 2016.", 
};
const char *d_para[5] = 
{
	"India is a country known for its values since biblical times. We begin to learn moral values from our family. Here children are taught to respect their elders, greet them properly whenever they meet them. A child knows that he should obey his elders whatever is ask him to do. There are many examples from history which have represented the importance of moral values in life. One such example was when Lord Ram was asked to go to fourteen years in exile. Lord Ram could have denied it, But to keep his father's words, he accepted the exile graciously and went into exile.", 
	"Moral values are the principles of good and evil, which shows a person's behavior and judgments. A person may embrace moral values from society and government, religion, or self. They are derived from the family as well. Moral values can be adjusted to some extent if they become a cause of pressure. Teens these days are more inclined towards seeking happiness rather than esteeming moral values. This may be attributed to the growing influence of western culture.", 
	"Population explosion is a big concern in today's age. There are many reasons why the population is increasing so rapidly. One of the major reason is the illiteracy among the people. We see high population growth where there are poverty and illiteracy. Illiterate people are generally unaware of the birth control and usage of it. Also, poor people tend to marry at a young age without any sex education and end up having many kids. One of the other reasons for the population explosion is the development of science and medicine. The life expectancy of people has increased drastically.", 
	"Population explosion more than often comes under negative limelight. It is so because more population means more exploitation of natural resources, and it isn't good for the environment. It leads to the devastation of flora and fauna in that place. More population means more industrialization, which means more pollution of water and air. It also leads to inequitable distribution of the money i.e., per capita income of the country drops. The higher population needs more investment for better infrastructure. If the government cannot provide that, it leads to a poor standard of living. It becomes difficult for the government to provide employment. It sometimes leads the unemployed youth to the path of crime, and thus the country becomes a bad neighborhood to live. The food produced every year is insufficient, and it becomes costly. Because of which the prices of other useful items also increase. It has also been seen that where the population is high, the status of women is subordinate.", 
	"On April 18, 1982, on the event of a symposium organized by ICOMOS International Council of Monuments and Sites in Tunisia, the holding of the “International Day for Sites & Monuments” to be celebrated together throughout the world was suggested. The idea was also stamped by the UNESCO General Conference, which cleared a resolution at its 22nd session in Nov 1983, recommending that the Member States examine the chances of declaring April 18 each year “International Sites & Monuments Day.” This has been called the World Heritage Day since then. World heritage day could be celebrated by doing different things. Few suggestions of ICOMOS are by going to the sites and relishing the culture and monuments. Restoration works are done for free of the dilapidated monuments—advertising about the monuments through articles in newspapers and ads in televisions. Many exhibitions are done with paintings and posters. Many foreign experts are invited, and press conferences are held to increase awareness in the world."
};  
const char *s_para[5] = 
{
	"The international worker's day or international labour's day marks the end of exploitation, prolonged working hours, maltreatment towards the labourers and working classes across the continents.  In the late 1800s, the labour union initiated a movement to raise their voice against the unfair and unjust treatment toward labourers.", 
	"International labour's day is observed to celebrate the efforts of the working classes in building the nation's economy.  The annual celebration of labour's day symbolizes the victory of the labour union movement for promoting the welfare of the labourers.", 
	"Labour's day is marked as a remembrance of their victory.  It is celebrated with pomp and show with street parades, parties, and unique athletic events.  The workers are the backbone of every nation.  A country cannot see economic progress and industrial growth without the contribution of workers.   Thus, on International labour's day, we can pay our gratitude to all the workers.", 
	"The day marks an important day, and on this very occasion, the Technology Development Board awards the contribution of fellow citizens in the field of science and technology. This is how the Technology Development Board celebrates National Technology Day.", 
	"India, after the successful testing at Pokhran, became the sixth full-fledged nuclear country of the world. The operation was originally named ” operation Shakti-98,” there were five nuclear devices. India's first indigenous aircraft, Hansa 3, was tested on the same day, i.e., the 11th day of May 1998 at Banglore."
};
#endif